"""Campaign kit ZIP assembly — copy + image + audio + rationale."""
from __future__ import annotations

import zipfile
from pathlib import Path
from datetime import datetime

KITS_DIR = Path(__file__).parent.parent / "demo" / "kits"
KITS_DIR.mkdir(parents=True, exist_ok=True)


def assemble_kit(
    brand_id: str,
    copy: str,
    audio_script: str,
    image_path: Path | None = None,
    audio_path: Path | None = None,
) -> Path:
    """
    Assemble deliverables into a ZIP kit.
    Returns path to the ZIP file.
    """
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    kit_path = KITS_DIR / f"{brand_id}_campaign_{ts}.zip"

    with zipfile.ZipFile(kit_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("copy.md", copy)
        zf.writestr("audio_scripts.md", audio_script)

        if image_path and Path(image_path).exists():
            zf.write(image_path, f"images/{Path(image_path).name}")

        if audio_path and Path(audio_path).exists():
            zf.write(audio_path, f"audio/{Path(audio_path).name}")

        zf.writestr("manifest.json", f'{"brand_id": "{brand_id}", "generated": "{ts}", "version": "3.0.0"}')
        zf.writestr("README.md", f"""# BrandMind Campaign Kit
Brand: {brand_id}
Generated: {ts}

## Contents
- copy.md — Headlines, body, CTA, social posts
- audio_scripts.md — 15s / 30s / 60s scripts
- images/ — Campaign visuals (flux-schnell)
- audio/ — Synthesized audio spots (Fish Audio)

Generated by BrandMind Sovereign v3.0
""")

    return kit_path
